# Generated by Django 3.2.5 on 2021-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Remark',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=100)),
                ('name', models.CharField(max_length=100, null=True)),
                ('message', models.TextField(max_length=250)),
                ('remarks', models.CharField(max_length=100, null=True)),
            ],
        ),
    ]
