# Generated by Django 2.1.5 on 2021-09-30 06:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whishlists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='automobilewishlist',
            name='automobile_status',
            field=models.CharField(default='unavailable', max_length=100),
        ),
        migrations.AddField(
            model_name='productwishlist',
            name='product_status',
            field=models.CharField(default='unavailable', max_length=100),
        ),
    ]
