# Generated by Django 2.1.5 on 2021-09-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('whishlists', '0002_auto_20210930_1203'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='automobilewishlist',
            name='product_name',
        ),
        migrations.AddField(
            model_name='automobilewishlist',
            name='automobile_name',
            field=models.CharField(default='truck', max_length=100),
        ),
    ]
