# Generated by Django 2.1.5 on 2021-09-22 18:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyAdmin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150, null=True)),
                ('username', models.CharField(max_length=150)),
                ('password', models.CharField(max_length=100)),
                ('last_login', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
    ]
