# Generated by Django 2.1.5 on 2021-09-22 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmins', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myadmin',
            name='name',
        ),
        migrations.AddField(
            model_name='myadmin',
            name='first_name',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='myadmin',
            name='last_name',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
