# Generated by Django 2.1.5 on 2021-09-22 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
        ('orders', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order2',
            old_name='user',
            new_name='product_id',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='product',
        ),
        migrations.AddField(
            model_name='order2',
            name='user_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
    ]
