# Generated by Django 2.1.5 on 2021-09-22 06:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0002_auto_20210922_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='order2',
            old_name='product_id',
            new_name='product',
        ),
        migrations.RenameField(
            model_name='order2',
            old_name='user_id',
            new_name='user',
        ),
    ]
