# Generated by Django 2.1.5 on 2021-09-22 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_auto_20210922_1228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order2',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='user_id',
        ),
    ]
