# Generated by Django 2.1.5 on 2021-09-22 06:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0001_initial'),
        ('orders', '0007_order2_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order2',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order2',
            name='product',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='products.Product'),
        ),
        migrations.AddField(
            model_name='order2',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
