# Generated by Django 2.1.5 on 2021-09-27 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0008_auto_20210922_1231'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order2',
            name='product',
        ),
        migrations.RemoveField(
            model_name='order2',
            name='user',
        ),
        migrations.AddField(
            model_name='order2',
            name='customer_name',
            field=models.CharField(default='noname', max_length=200),
        ),
    ]
