# Generated by Django 3.2.5 on 2021-09-21 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=150)),
                ('rate', models.FloatField(default=10.1, null=True)),
                ('status', models.CharField(choices=[('available', 'available'), ('unavailable', 'unavailable')], default='available', max_length=20)),
            ],
        ),
    ]
