# Generated by Django 2.1.5 on 2021-09-25 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insiders', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppliedInsider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('email', models.CharField(max_length=150)),
                ('address', models.CharField(max_length=150)),
                ('profession', models.CharField(max_length=150)),
                ('businessState', models.BooleanField(default=True)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
    ]
