# Generated by Django 2.1.5 on 2021-09-27 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insiders', '0002_appliedinsider'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AppliedInsider',
        ),
    ]
